#!/usr/bin/env node

/**
 * Sync the version from package.json into src/update/version.ts.
 *
 * This runs as a prebuild step so that CURRENT_VERSION is always
 * derived from the single source of truth (package.json), avoiding
 * dual maintenance. The generated file is committed to the repo so
 * that lint/typecheck work without a build step.
 *
 * Usage: node scripts/sync-version.js
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, '..');

const pkg = JSON.parse(readFileSync(join(rootDir, 'package.json'), 'utf-8'));
const version = pkg.version;

const content = `// Auto-generated by scripts/sync-version.js — do not edit manually.
// Source of truth: package.json "version" field.
export const CURRENT_VERSION = '${version}';
`;

const targetPath = join(rootDir, 'src', 'update', 'version.ts');

// Only write if content changed to avoid unnecessary rebuilds.
try {
  const existing = readFileSync(targetPath, 'utf-8');
  if (existing === content) {
    process.exit(0);
  }
} catch {
  // File doesn't exist yet — write it.
}

writeFileSync(targetPath, content, 'utf-8');
console.log(`Synced version ${version} → src/update/version.ts`);
