// Auto-generated by scripts/sync-changelog.js — do not edit manually.
// Source of truth: CHANGELOG.md

export interface ChangelogEntry {
  readonly version: string;
  readonly date: string;
  readonly changes: string;
}

export const CHANGELOG: readonly ChangelogEntry[] = [
  {
    version: 'v0.5.0',
    date: '2026-04-09',
    changes:
      'Ethereum mainnet support via Paraswap swaps, Aave V3 lending, and Hyperliquid perpetuals — the second chain to ship on the multi-chain architecture.',
  },
  {
    version: 'v0.4.0',
    date: '2026-03-26',
    changes:
      'Config tamper protection and restart command to prevent prompt-injected agents from silently changing guardrails.',
  },
  {
    version: 'v0.3.0',
    date: '2026-03-26',
    changes: 'Documentation site, SEO optimization, and contributor experience improvements.',
  },
  {
    version: 'v0.2.0',
    date: '2026-03-25',
    changes:
      'Daemon tier, AlphaLend lending, activity query engine, wallet import by private key, expanded token registry, unified activities table, and TUI polish.',
  },
  {
    version: 'v0.1.0',
    date: '2026-03-18',
    changes: 'Initial release of OnlyFence — agent wallet guardrails for DeFi.',
  },
];
